version: 2.1

jobs:
  build:
    docker:
    - image: cimg/python:3.11
    steps:
    - checkout
    - run: python main.py
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python test.py
  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - run: echo "deploying image to production server"

          

workflows:
  build_now:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
           - test
          filters:
            branches:
              only: main


